/// Flutter icons AnaZone
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AnaZone
///      fonts:
///       - asset: fonts/AnaZone.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AnaZone {
  AnaZone._();

  static const _kFontFam = 'AnaZone';
  static const String? _kFontPkg = null;

  static const IconData map_search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android_messages = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
